server:
  port: 8701
eureka:
  instance:
    hostname: 35.186.154.84
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://35.186.154.84:8761/eureka}
zuul:
  prefix: /api
  routes:
    db-service:
      path: /db-service/*
      service-id: DB-SERVICE