info:
  app:
    name: gateway-api
server:
  port: 8701
eureka:
  instance:
    hostname: localhost
    preferIpAddress: true
  client:
    fetchRegistry: true
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://eureka.server.com:8761/eureka}
spring:
  application:
    name: gateway-api
  boot:
    admin:
      client:
        url:
        - http://localhost:8088
        username: admin
        password: admin
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
      - id: db-service
        uri: lb://db-service
        predicates:
        - Path=/db-service/**
        filters:
        - RewritePath=/db-service/(?.*), /$\{path}
security:
  basic:
    enable: false