info:
  app:
    name: gateway-api
server:
  port: 8701
eureka:
  instance:
    hostname: localhost
    preferIpAddress: true
  client:
    fetchRegistry: true
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://eureka.server.com:8761/eureka}
spring:
  application:
    name: gateway-api
security:
  basic:
    enable: false
zuul:
  prefix: /api
  routes:
    db-service:
      path: /db-service/*
      service-id: DB-SERVICE
ribbon:
  ReadTimeout: 30000
  ConnectTimeout: 30000
  MaxAutoRetries: 1
  MaxAutoRetriesNextServer: 1