spring:
  application:
    name: stock-service
server:
  port: 8802
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_URI:http://eureka.server.com:8761/eureka}
  instance:
    hostname: localhost
    preferIpAddress: true
db-service:
  name: db-service
  ribbon:
    eureka:
      enabled: false
    listOfServers: localhost:8801
    ServerListRefreshInterval: 15000
rest:
  db-service:
    signal-data: /rest/db/signal-data