info:
  app:
    name: stock-service
spring:
  application:
    name: stock-service
server:
  port: 8901
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_URI:http://eureka.server.com:8761/eureka}
  instance:
    hostname: localhost
    preferIpAddress: true
db-service:
  name: localhost:8701
  ribbon:
    listOfServers: localhost:8801
    ServerListRefreshInterval: 15000
rest:
  db-service:
    signal-data: /api/db-service/rest/db/signal-data
ribbon:
  eager-load:
    clients:
    - 