spring:
  application:
    name: stock-service
server:
  port: 8901
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_URI:http://eureka.server.com:8761/eureka}
  instance:
    hostname: localhost
    preferIpAddress: true
db-server:
  host: localhost
  port: 8801
  rest:
    signal-data: /rest/db/signal-data