server:
  port: 8700
spring:
  cloud:
    config:
      server:
        git:
          url: config
  boot:
    admin:
      client:
        url:
        - http://localhost:8080
        username: admin
        password: admin
management:
  security:
    enabled: false
  endpoints:
    web:
      exposure:
        include: '*'