server:
  port: 8761
eureka:
  server:
    wait-time-in-ms-when-sync-empty: 0
  instance:
    leaseRenewalIntervalInSeconds: 10
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      default-zone: http://localhost:${server.port}/eureka/
spring:
  application:
    name: discovery-service
  boot:
    admin:
      client:
        url:
        - http://localhost:8088
        username: admin
        password: admin